name: Deploy • VPS via password (Production)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag d'image à déployer (ex: latest, 1.3, <sha court>)"
        required: true
        default: "latest"

concurrency:
  group: deploy-production
  cancel-in-progress: false

env:
  SERVICE: api
  IMAGE: kysaymeric/pavillon-les-lys
  DEPLOY_DIR: /home/sk_aymeric/pavillon-lys-api
  ENV_URL: http://51.254.33.99:3000 # remplace par ton domaine si tu en as un

jobs:
  deploy:
    runs-on: ubuntu-latest

    # ✅ Badge "Deployed to production" + historique côté GitHub
    environment:
      name: production
      url: ${{ env.ENV_URL }}

    permissions:
      contents: read
      deployments: write # nécessaire pour créer/mettre à jour un "Deployment" GitHub

    steps:
      - name: Create GitHub Deployment
        id: create_deployment
        uses: actions/github-script@v7
        with:
          script: |
            const res = await github.request('POST /repos/{owner}/{repo}/deployments', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'production',
              auto_merge: false,
              required_contexts: []
            });
            core.setOutput('deployment_id', res.data.id);

      - name: SSH & deploy (password auth, bash + debug)
        id: ssh_deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          command_timeout: 30m
          script_stop: true
          script: |
            bash -lc '
              set -euxo pipefail
              set -x
              SERVICE="${{ env.SERVICE }}"
              DEPLOY_DIR="${{ env.DEPLOY_DIR }}"
              IMAGE_TAG="${{ github.event.inputs.tag }}"
              PASS="${{ secrets.VPS_PASSWORD }}"

              echo "== Check directory =="
              if [ ! -d "$DEPLOY_DIR" ]; then
                echo "❌ Directory $DEPLOY_DIR does not exist"
                exit 10
              fi
              ls -ld "$DEPLOY_DIR"
              cd "$DEPLOY_DIR"
              echo "✅ Working directory: $(pwd)"

              echo "== Check Docker & Compose =="
              # Vérifier Docker
              DOCKER_AVAILABLE=false
              DOCKER_NEEDS_SUDO=false
              
              if docker --version >/dev/null 2>&1; then
                DOCKER_AVAILABLE=true
                echo "✅ Docker available"
                docker --version
              elif echo "$PASS" | sudo -S docker --version >/dev/null 2>&1; then
                DOCKER_AVAILABLE=true
                DOCKER_NEEDS_SUDO=true
                echo "✅ Docker available with sudo"
                echo "$PASS" | sudo -S docker --version
              else
                echo "❌ Docker not available"
                exit 11
              fi

              # Vérifier Docker Compose
              COMPOSE_AVAILABLE=false
              COMPOSE_NEEDS_SUDO=false
              
              if docker compose version >/dev/null 2>&1; then
                COMPOSE_AVAILABLE=true
                echo "✅ Docker Compose V2 available"
                docker compose version
              elif command -v docker-compose >/dev/null 2>&1; then
                COMPOSE_AVAILABLE=true
                echo "✅ Docker Compose V1 available"
                docker-compose version
              elif echo "$PASS" | sudo -S docker compose version >/dev/null 2>&1; then
                COMPOSE_AVAILABLE=true
                COMPOSE_NEEDS_SUDO=true
                echo "✅ Docker Compose V2 available with sudo"
                echo "$PASS" | sudo -S docker compose version
              elif echo "$PASS" | sudo -S docker-compose version >/dev/null 2>&1; then
                COMPOSE_AVAILABLE=true
                COMPOSE_NEEDS_SUDO=true
                echo "✅ Docker Compose V1 available with sudo"
                echo "$PASS" | sudo -S docker-compose version
              fi

              if [ "$COMPOSE_AVAILABLE" = false ]; then
                echo "❌ Docker Compose not found. Install with:"
                echo "sudo apt-get update && sudo apt-get install -y docker-compose-plugin"
                echo "or for older versions: sudo apt-get install -y docker-compose"
                exit 12
              fi

              echo "== Docker Hub login (optional) =="
              if [ -n "${{ secrets.DOCKERHUB_USERNAME || '' }}" ]; then
                echo "Attempting Docker Hub login..."
                if echo "${{ secrets.DOCKERHUB_TOKEN || '' }}" | run_docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin 2>/dev/null; then
                  echo "✅ Docker Hub login successful"
                else
                  echo "⚠️ Docker Hub login failed, continuing anyway"
                fi
              else
                echo "No Docker Hub credentials provided, skipping login"
              fi

              echo "== Helper functions =="
              run_docker() {
                if [ "$DOCKER_NEEDS_SUDO" = true ]; then
                  echo "$PASS" | sudo -S docker "$@"
                else
                  docker "$@"
                fi
              }

              run_compose() {
                if [ "$COMPOSE_NEEDS_SUDO" = true ]; then
                  if echo "$PASS" | sudo -S docker compose version >/dev/null 2>&1; then
                    echo "$PASS" | sudo -S docker compose "$@"
                  else
                    echo "$PASS" | sudo -S docker-compose "$@"
                  fi
                else
                  if docker compose version >/dev/null 2>&1; then
                    docker compose "$@"
                  else
                    docker-compose "$@"
                  fi
                fi
              }

              echo "== Capture pre-deployment image =="
              PRE_IMAGE=$(run_docker ps --filter "name=^/pavillon-api$" --format "{{.Image}}" 2>/dev/null || echo "none")
              echo "PRE_IMAGE=$PRE_IMAGE"

              echo "== Update .env IMAGE_TAG =="
              if [ -f .env ]; then
                echo "Found existing .env file"
                if grep -q "^IMAGE_TAG=" .env; then
                  sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=${IMAGE_TAG}/" .env
                  echo "✅ Updated existing IMAGE_TAG in .env"
                else
                  echo "IMAGE_TAG=${IMAGE_TAG}" >> .env
                  echo "✅ Added IMAGE_TAG to existing .env"
                fi
              else
                echo "IMAGE_TAG=${IMAGE_TAG}" > .env
                echo "✅ Created new .env with IMAGE_TAG"
              fi
              
              echo "Current .env content:"
              cat .env
              echo "--- end of .env ---"

              echo "== Pull & Deploy service: ${SERVICE} =="
              echo "Pulling latest image for ${SERVICE}..."
              if ! run_compose pull "${SERVICE}"; then
                echo "❌ Failed to pull image for ${SERVICE}"
                exit 13
              fi
              echo "✅ Image pulled successfully"

              echo "Starting/updating ${SERVICE}..."
              if ! run_compose up -d "${SERVICE}"; then
                echo "❌ Failed to start/update ${SERVICE}"
                exit 14
              fi
              echo "✅ Service ${SERVICE} started/updated successfully"

              echo "== Capture post-deployment image =="
              sleep 3  # Wait a moment for container to start
              POST_IMAGE=$(run_docker ps --filter "name=^/pavillon-api$" --format "{{.Image}}" 2>/dev/null || echo "none")
              echo "POST_IMAGE=$POST_IMAGE"

              echo "== Deployment summary =="
              DATE_UTC=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
              echo "::notice title=Deployment::${SERVICE} déployé avec le tag ${IMAGE_TAG}"
              
              echo "========================================="
              echo "🚀 DEPLOYMENT SUMMARY"
              echo "========================================="
              echo "SERVER=${{ secrets.VPS_HOST }}"
              echo "SERVICE=${SERVICE}"
              echo "TAG=${IMAGE_TAG}"
              echo "PRE_IMAGE=${PRE_IMAGE}"
              echo "POST_IMAGE=${POST_IMAGE}"
              echo "DATE=${DATE_UTC}"
              echo "DEPLOY_DIR=${DEPLOY_DIR}"
              echo "========================================="

              echo "== Cleanup old images =="
              if run_docker image prune -f; then
                echo "✅ Image cleanup completed"
              else
                echo "⚠️ Image cleanup failed, but deployment was successful"
              fi

              echo "== Final status check =="
              echo "Container status:"
              run_docker ps --filter "name=pavillon-api" --format "table {{.Names}}\\t{{.Status}}\\t{{.Image}}" || echo "Could not get container status"
              
              echo "✅ Deployment completed successfully!"
            '

      - name: Publish Job Summary
        run: |
          {
            echo "## 🚀 Déploiement — Pavillon Les Lys (production)";
            echo "";
            echo "**Tag déployé :** \`${{ github.event.inputs.tag }}\`";
            echo "**Service :** \`${{ env.SERVICE }}\`";
            echo "**Serveur :** \`${{ secrets.VPS_HOST }}\`";
            echo "**Dossier de déploiement :** \`${{ env.DEPLOY_DIR }}\`";
            echo "**URL :** ${{ env.ENV_URL }}";
            echo "";
            echo "_Consulte les logs pour voir l'image avant/après et l'heure UTC._";
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Set Deployment Status (success)
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.request('POST /repos/{owner}/{repo}/deployments/{deployment_id}/statuses', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.create_deployment.outputs.deployment_id }},
              state: 'success',
              environment: 'production',
              environment_url: process.env.ENV_URL,
              log_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });

      - name: Set Deployment Status (failure)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.request('POST /repos/{owner}/{repo}/deployments/{deployment_id}/statuses', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.create_deployment.outputs.deployment_id }},
              state: 'failure',
              environment: 'production',
              environment_url: process.env.ENV_URL,
              log_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });
